services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PASSWORD_P}
      PGDATA: /data/postgres
    volumes:
      - db_data:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db_network
    restart: unless-stopped

networks:
  db_network:
    driver: bridge

volumes:
  db_data: